- name: Create a new IAM role
  iam_role:
    region: "{{ region }}"
    profile: "{{ aws_account_name }}"
    name: "{{ item.name }}"
    path: '/'
    state: present
    assume_role_policy_document: "{{ item.trust_policy }}"
    managed_policy: "{{ item.managed_policies|default([]) }}"
  with_items: "{{ dynamic_iam_roles|default([]) }}"
  register: iam_role

# See this http://stackoverflow.com/questions/36419442/the-role-defined-for-the-function-cannot-be-assumed-by-lambda
# Without this I hit the error The role defined for the function cannot be assumed by Lambda
- name: Sleeping for 10 sec for the role to be available.
  pause: seconds=10
  when: iam_role.changed

- name: Create and attach policy to role
  iam_policy:
    region: "{{ region }}"
    profile: "{{ aws_account_name }}"
    iam_type: role
    iam_name: "{{ item.name }}"
    policy_name: "{{ item.policy_name | default(item.name) }}"
    policy_json: "{{ item.policy }}"
    state: present
  with_items: "{{ dynamic_iam_roles|default([]) }}"
  when: item.policy | default()
  register: iam_policy

- name: Sleeping for 10 sec for the role to be available.
  pause: seconds=10
  when: iam_policy.changed
